### ISSUE TITLE
Are Provider tab-completers functional?

### ISSUE THREAD

**Issue by jonahseguin** [xxyy/intake-spigot#10]
Just wondering if the getSuggestions() method is actually used internally by a bukkit tab completion system?  From my testing, my providers aren't providing tab-completion arguments.

Example usage:
```java
@Override
    public List<String> getSuggestions(String s) {
        return Core.getInstance().getProfileCache().getOnlineProfiles()
                .stream()
                .map(Profile::getUsername)
                .filter(name -> name.toLowerCase().contains(s.toLowerCase()) || s.length() == 0)
                .collect(Collectors.toList());
    }
```

**Comment by literalplus** [comment]
iirc they're not actually used. But there is some way, probably related to the `Command` class, which Intake-Spigot overrides. Don't remember exactly. Surefire way is to catch the tab-complete request event. (My Plugin xxyy/commandblockerultimate does that, but for something else)

**Comment by literalplus** [comment]
okay it's actually in our README, we seem to need something along the lines of this: https://github.com/EngineHub/Intake/pull/23 for it to work. It's not listed in the xxyy/Intake readme, so probably not there yet. Also the behaviour might have changed in recent Minecraft versions, but I doubt that

**Comment by jonahseguin** [comment]
https://github.com/MyWarp/Intake/commit/9957397b9a5f5107560e0b6c05b24509aaa0c608

The getSuggestions method signature has changed upstream it seems, see MyWarp/Intake in general for quite a bit of progression.

I feel as though we could simply implement a tab completer like so for the plugin automatically and it could work?

```java
import li.l1t.common.intake.CommandsManager;
import li.l1t.common.intake.IntakeCommand;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;

import java.util.List;
import java.util.stream.Collectors;

public class TabCompleteEx implements TabCompleter {

    private CommandsManager commandsManager;

    @Override
    public List<String> onTabComplete(CommandSender commandSender, Command command, String alias, String[] args) {
        IntakeCommand intakeCommand = commandsManager.getCommand(command.getName());
        Location location = null;
        if (commandSender instanceof Player) {
            location = ((Player) commandSender).getLocation();
        }
        return intakeCommand.tabComplete(commandSender, alias, args).stream().limit(10).collect(Collectors.toList());
    }

    // then somewhere in intake
    void register() {
        // ex when the command is registered using commandsmanager#registerCommand
        commandsManager.getPlugin().getServer().getPluginCommand("the name of the command").setTabCompleter(this);
        // instead of the `this` call it'd obviously be a local tab completer instance stored in the commands manager?
    }

}

```

**Comment by jonahseguin** [comment]
@xxyy here's what I suggest:
https://github.com/jonahseguin/intake-spigot/commit/60afddcc59b2b68fc46b6d4f79b3d791a1d88d8b
will open a PR if you think this is functional

**Comment by literalplus** [comment]
Thanks for the research! `IntakeCommand` already has a method for tab-compeltion, could we register this instead of having a separate class for it? https://github.com/jonahseguin/intake-spigot/blob/60afddcc59b2b68fc46b6d4f79b3d791a1d88d8b/src/main/java/li/l1t/common/intake/IntakeCommand.java#L143

Also, you don't need to add your name to every line, it's in the Git history anyways :)

**Comment by jonahseguin** [comment]
@xxyy See https://github.com/jonahseguin/intake-spigot/commit/dfc302f81167995035906328568d7ffbb293de8f
I accidentally committed my pom too, whoops

**Comment by jonahseguin** [comment]
Still interested in this.

**Comment by literalplus** [comment]
Than for the reminder @jonahseguin! Quite busy atm which means that such things get lost quickly :) Looks fine to me, added a small comment. Can you open a PR for this? Then it's also easier to review and everything is in one place!

I notice you committed the changes to `master` in your repo, for the PR please create a separate branch with only the relevant changes. GitHub has a few guides for this if you need: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by literalplus** [comment]
As you may or may not have guessed by there not being any updates in the past four years, I no longer have the resources to maintain this project. Thanks for your interest & hope you were able to otherwise resolve your issue in the meantime! :)
