### ISSUE TITLE
Ability to customize the generated help menu

### ISSUE THREAD

**Issue by jonahseguin** [xxyy/intake-spigot#7]
When you type a command without a subcommand argument, it displays a list of commands in gold.

This is automatically generated.

I'd like to be able to format this generated help menu, (specifically change the colors at the very least, from the default gold/yellow)

some kind of commandsManager.withHelpFormatter(formatter) type thing.

I've looked through the code but I'm not sure how to implement this.  @xxyy

**Comment by xxyy** [comment]
Hello,

thanks for your interest in the project! :) You can customise the content
of the messages by calling CommandBuilder.setTranslator(). Take a look at
ResourceBundleTranslator for an example (change the bundle key - a
constructor parameter would be a useful addition to that class). xxyy/expvp
might have an example of this.

For the colours, sadly, it's not as easy. Those are hard-coded in
CommandHelpExtractor, e.g.
https://github.com/xxyy/intake-spigot/blob/b4abadd18c0e93c4c3b5ce4f9ddb1b31f7026bda/src/main/java/li/l1t/common/intake/help/CommandHelpExtractor.java#L77.
Probably the easiest way to have basic customisation here is to add a
setter/constructor parameter for primary/secondary colour to that class.

The instances of that class are created in CommandHelpProvider, which is
accessible from CommandsManager. So, adding setters there too (and passing
the colours on) would be enough to be able to set them from a plugin.

This principle can easily be extended to be a little cleaner (separating
implementation details from CommandHelpProvider) with something like a
ColorSchemeProvider interface. This would have methods to get
primary/secondary colours. The default implementation would return colours
as-is, but you'd have a setter on CommandHelpProvider for
ColorSchemeProvider so you could provide your own colours.

PRs appreciated :) I'm personally a little busy at the moment sadly.

Hope this helps!

**Comment by literalplus** [comment]
Hello,

thanks for your interest in the project! :) You can customise the content
of the messages by calling CommandBuilder.setTranslator(). Take a look at
ResourceBundleTranslator for an example (change the bundle key - a
constructor parameter would be a useful addition to that class). xxyy/expvp
might have an example of this.


For the colours, sadly, it's not as easy. Those are hard-coded in
CommandHelpExtractor, e.g.
https://github.com/xxyy/intake-spigot/blob/b4abadd18c0e93c4c3b5ce4f9ddb1b31f7026bda/src/main/java/li/l1t/common/intake/help/CommandHelpExtractor.java#L77.
Probably the easiest way to have basic customisation here is to add a
setter/constructor parameter for primary/secondary colour to that class.

The instances of that class are created in CommandHelpProvider, which is
accessible from CommandsManager. So, adding setters there too (and passing
the colours on) would be enough to be able to set them from a plugin.

This principle can easily be extended to be a little cleaner (separating
implementation details from CommandHelpProvider) with something like a
ColorSchemeProvider interface. This would have methods to get
primary/secondary colours. The default implementation would return colours
as-is, but you'd have a setter on CommandHelpProvider for
ColorSchemeProvider so you could provide your own colours.

PRs appreciated :) I'm personally a little busy at the moment sadly.

Hope this helps!

**Comment by jonahseguin** [comment]
Was able to work around this issue for one of my commands for now, but I plan on implementing a HelpFormatter or alike system, with command-specific formatting possible.

```java
@Command(aliases = {"help", "commands", ""}, desc = "Factions help.", help = "View factions commands, and info about the plugin.", usage = "[page = 1]")
    public void factionsHelp(@Sender HCFPlayer sender, @Optional("1") int page) {
        sender.msg(HCFLang.HEADER_FOOTER);
        sender.msg(HCFLang.FACTION_CMD_ROOT_HEADER);
        sender.msg(HCFLang.FACTION_CMD_ROOT_INFO, this.hcf.getDescription().getVersion());
        sender.msg(HCFLang.FACTION_CMD_HELP_HOVER);

        CommandMapping mapping = this.hcf.getCommands().getFactionsDispatcher().get("factions");
        if (mapping != null) {
            CommandCallable callable = mapping.getCallable();
            if (callable instanceof Dispatcher) {
                Dispatcher dispatcher = (Dispatcher) callable;

                Set<CommandMapping> commands = new HashSet<>();

                for (Iterator<CommandMapping> it = dispatcher.getCommands().iterator(); it.hasNext(); ) {
                    CommandMapping m = it.next();
                    CommandCallable cc = m.getCallable();
                    if (cc instanceof Dispatcher) {
                        Dispatcher d = (Dispatcher) cc;
                        commands.addAll(d.getCommands());
                    }
                    else {
                        commands.add(m);
                    }
                }

                Pagination pagination = new Pagination(commands.size(), 10, 1);

                if (page > pagination.getNumberOfPages()) {
                    sender.msg(HCFLang.FACTION_CMD_HELP_INSUFF_PAGES, pagination.getNumberOfPages());
                    return;
                }
                if (page < 1) {
                    page = 1;
                }
                pagination.setPage(page);

                pagination.getItems(Lists.newArrayList(commands)).forEach(cmd -> {
                    boolean hasPermission = true;
                    for (String perm : cmd.getDescription().getPermissions()) {
                        if (!sender.hasPermission(perm)) {
                            hasPermission = false;
                            break;
                        }
                    }
                    if (hasPermission) {
                        describeCommand(sender, cmd.getPrimaryAlias(), cmd.getDescription().getUsage(), cmd.getDescription().getShortDescription(), cmd.getDescription().getHelp());
                    }
                });

                sender.msg(HCFLang.FACTION_CMD_HELP_PAGE, page, pagination.getNumberOfPages(), pagination.getStartIndexStr(), pagination.getEndIndexStr(), pagination.getSize());
            }
        }


        sender.msg(HCFLang.HEADER_FOOTER);
    }

    private void describeCommand(HCFPlayer sender, String name, String usage, String desc, String help) {
        sender.msgBuilder(HCFLang.FACTION_CMD_HELP_ENTRY, componentBuilder -> componentBuilder
                .event(new HoverEvent(HoverEvent.Action.SHOW_TEXT,
                        TextComponent.fromLegacyText(this.hcf.getLang().getFormattedLang(HCFLang.FACTION_CMD_HELP_TOOLTIP, name, help))
                ))
                .event(new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, "/f " + name))
                .create(), name, usage, desc);
    }
```

The getFactionsDispatcher is provided simply by storing the variable returned from `getDispatcher` after building a command using `startRegistration`:

```java
this.factionsDispatcher = this.commandsManager.startRegistration(new CmdFactions(hcf), "factions", "faction", "f", "fac", "team", "t", "squad", "sq", "squads", "teams")
                .withSubHandler(new CmdFAdminClaim(hcf))
                ...
                .create()
                .register()
                .getDispatcher();
```

**Comment by literalplus** [comment]
As you may or may not have guessed by there not being any updates in the past four years, I no longer have the resources to maintain this project. Thanks for your interest & hope you were able to otherwise resolve your issue in the meantime! :)
