### ISSUE TITLE
The Maven Library is Unavailable

### ISSUE THREAD

**Issue by Onyxtite** [xxyy/intake-spigot#8]
Self - Explanatory. The webpage is down.

**Comment by literalplus** [comment]
yeah, sorry for that! Currently having an issue with my OpenShift setup
that I won't get around to fix that soon probably. :/ Please check out the
library on your computer (pay attention to the correct version number) and
use "mvn clean install" to install locally and override the remote version
for the time being.

**Comment by jonahseguin** [comment]
@xxyy not sure if this is the same issue, but it seems a cert has expired
```
Could not resolve dependencies for project li.l1t.common:intake-spigot:jar:4.2.36-SNAPSHOT:
 Failed to collect dependencies at org.spigotmc:spigot-api:jar:1.8.8-R0.1-SNAPSHOT: Failed to read
 artifact descriptor for org.spigotmc:spigot-api:jar:1.8.8-R0.1-SNAPSHOT: Could not transfer artifact org.spigotmc:spigot-api:pom:1.8.8-R0.1-SNAPSHOT from/to xxyy-public 
(https://repo.l1t.li/xxyy-public/): sun.security.validator.ValidatorException: PKIX path validation 
failed: java.security.cert.CertPathValidatorException:
 timestamp check failed: NotAfter: Thu May 16 10:55:46 MDT 2019 -> [Help 1]
```

**Comment by literalplus** [comment]
@jonahseguin Thanks, I missed replacing the certificate for that route! Now the 503 Service Unavailable page is served securely again :(

**Comment by literalplus** [comment]
As you may or may not have guessed by there not being any updates in the past four years, I no longer have the resources to maintain this project. Thanks for your interest & hope you were able to otherwise resolve your issue in the meantime! :)
